USE info2_i202853;

DROP TABLE IF EXISTS `BATIMENT`;
CREATE TABLE `BATIMENT`(
    `playerId` INT(11) NOT NULL,
    `type` VARCHAR(255) NOT NULL,
    `standardProduction` FLOAT NOT NULL,
    `level` INT(11) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS `RESSOURCES`;
CREATE TABLE `RESSOURCES`(
    `playerId` INT(11) NOT NULL,
    `bois` BIGINT(20) NOT NULL,
    `pierre` BIGINT(20) NOT NULL,
    `nourriture` BIGINT(20) NOT NULL,
    `villageois` BIGINT(20) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER`(
    `id` INT(11) NOT NULL,
    `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `lastTimeOnline` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(), `position` INT(11) DEFAULT NULL) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;
    
ALTER TABLE `RESSOURCES` 
	ADD PRIMARY KEY(`playerId`);


ALTER TABLE `USER` 
	ADD PRIMARY KEY(`id`),
    ADD UNIQUE KEY `username`(`username`);

ALTER TABLE `USER` 
	MODIFY `id` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `BATIMENT`
	ADD CONSTRAINT `lockPlayerId` FOREIGN KEY(`playerId`) REFERENCES `USER`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION;
    
ALTER TABLE `RESSOURCES`
	ADD CONSTRAINT `assignToPlayer` FOREIGN KEY(`playerId`) REFERENCES `USER`(`id`);

CREATE TRIGGER `createAccount` 
	AFTER INSERT ON `USER` 
    FOR EACH ROW
    INSERT INTO RESSOURCES(
        `playerId`,
        `bois`,
        `pierre`,
        `nourriture`,
        `villageois`
    ) VALUES(NEW.id, 500, 500, 500, 50)